package org.dg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("My Data Object")
public class Data implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "instance1")
   private java.lang.String instance1;
   @org.kie.api.definition.type.Label(value = "instance2")
   private java.lang.String instance2;

   public Data()
   {
   }

   public java.lang.String getInstance1()
   {
      return this.instance1;
   }

   public void setInstance1(java.lang.String instance1)
   {
      this.instance1 = instance1;
   }

   public java.lang.String getInstance2()
   {
      return this.instance2;
   }

   public void setInstance2(java.lang.String instance2)
   {
      this.instance2 = instance2;
   }

   public Data(java.lang.String instance1, java.lang.String instance2)
   {
      this.instance1 = instance1;
      this.instance2 = instance2;
   }

}