package org.dg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataObjectTest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int id;
   private java.lang.String data;

   public DataObjectTest()
   {
   }

   public int getId()
   {
      return this.id;
   }

   public void setId(int id)
   {
      this.id = id;
   }

   public java.lang.String getData()
   {
      return this.data;
   }

   public void setData(java.lang.String data)
   {
      this.data = data;
   }

   public DataObjectTest(int id, java.lang.String data)
   {
      this.id = id;
      this.data = data;
   }

}