package org.dg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyTestDataObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private long id;

   public MyTestDataObject()
   {
   }

   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   public MyTestDataObject(long id)
   {
      this.id = id;
   }

}