package org.dg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyTestDataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MyTestDataObject() {
    }

}